# Generated by Django 5.2.15 on 2026-07-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideastar',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ideastar',
            name='idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='ideaSite.idea'),
        ),
        migrations.RemoveField(
            model_name='ideastar',
            name='user',
        ),
    ]
