# Generated by Django 5.2.15 on 2026-07-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_actor_review_director_review_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
